#!/usr/bin/env python3
"""Test STT functionality for Groq and Nvidia"""
import asyncio
import sys
import os
sys.path.insert(0, os.path.join(os.getcwd(), 'backend'))

from app.voice.stt import GroqSTT
from app.voice.nvidia_stt import NvidiaSTT
from app.config import settings

async def test_stt():
    # We need a small audio file to test. 
    # If one doesn't exist, we can't really test the actual transcription without a file.
    # But we can test initialization and API connectivity if we had a sample.
    
    sample_audio_path = os.path.join(os.getcwd(), 'test_output.mp3') # Generated by test_tts.py
    
    if not os.path.exists(sample_audio_path):
        print(f"❌ Sample audio not found at {sample_audio_path}. Run test_tts.py first.")
        return False

    with open(sample_audio_path, 'rb') as f:
        audio_buffer = f.read()

    print(f"Testing STT with {len(audio_buffer)} bytes of audio...")

    # Test Groq STT
    try:
        print("\n--- Testing Groq Whisper ---")
        groq_stt = GroqSTT(api_key=settings.GROQ_API_KEY)
        transcript = await groq_stt.transcribe_stream(audio_buffer)
        if transcript:
            print(f"✅ Groq Success! Transcript: {transcript}")
        else:
            print("❌ Groq returned empty transcript")
    except Exception as e:
        print(f"❌ Groq Error: {e}")

    # Test Nvidia STT
    try:
        print("\n--- Testing Nvidia Whisper ---")
        nvidia_stt = NvidiaSTT(api_key=settings.NVIDIA_API_KEY)
        transcript = await nvidia_stt.transcribe_stream(audio_buffer)
        if transcript:
            print(f"✅ Nvidia Success! Transcript: {transcript}")
        else:
            print("❌ Nvidia returned empty transcript")
    except Exception as e:
        print(f"❌ Nvidia Error: {e}")

    return True

if __name__ == "__main__":
    if not settings.GROQ_API_KEY or settings.GROQ_API_KEY == "your_groq_api_key_here":
        print("❌ GROQ_API_KEY not set in .env")
        sys.exit(1)
    
    result = asyncio.run(test_stt())
    sys.exit(0 if result else 1)
